spring.application.name=User Service

#Porta do Servidor
server.port=3000

#Profile de Configuração
#spring.profiles.default=dev

#Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket-users

spring.datasource.password=postgres
spring.datasource.username=postgres